In [41]:
!pip install --force-reinstall numpy tensorflow==2.16.1 scikit-learn==1.5.0 pandas scikeras==0.13.0 gradio

  Using cached numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
  Using cached tensorflow-2.16.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.3 kB)
  Using cached scikit_learn-1.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
  Using cached pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
  Using cached scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
  Using cached gradio-5.29.0-py3-none-any.whl.metadata (16 kB)
  Using cached absl_py-2.2.2-py3-none-any.whl.metadata (2.6 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached h5py-3.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix


In [ ]:
#Carregando o dataset

base = pd.read_csv('/content/iris.csv')

#Visualizando as primeiras linhas do dataset
print(base.head())

#Visualizando as informações do dataset
print(base.info())


   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal length  150 non-null    float64
 1   sepal width   150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [ ]:
#Separando as features e as classes
X = base.iloc[:, 0:4].values
X
y = base.iloc[:, 4].values
y

#Convertendo as classes para valores numéricos
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)
y = np_utils.to_categorical(y)
y



array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
#Como temos 3 classes, vvamos utilizar soft-max de função de ativação
#Temos 4 neuronios de entrada e 3 de saida
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25)
X_treinamento.shape, X_teste.shape

((112, 4), (38, 4))

In [ ]:
y_treinamento.shape, y_teste.shape

((112, 3), (38, 3))

In [ ]:
rede_neural = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(4,)),
    tf.keras.layers.Dense(units=4, activation='relu'),
    tf.keras.layers.Dense(units=4, activation='relu'),
    tf.keras.layers.Dense(units=3, activation='softmax')
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(


In [ ]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
rede_neural.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])


In [ ]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size=10, epochs=1000)


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - categorical_accuracy: 0.9136 - loss: 0.1240 
Epoch 910/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - categorical_accuracy: 0.9468 - loss: 0.0880  
Epoch 911/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.9742 - loss: 0.0563 
Epoch 912/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - categorical_accuracy: 0.9775 - loss: 0.0541
Epoch 913/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - categorical_accuracy: 0.9792 - loss: 0.0671
Epoch 914/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - categorical_accuracy: 0.9800 - loss: 0.0570
Epoch 915/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - categorical_accuracy: 0.9800 - loss: 0.0592
Epoch 916/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - categorical_accuracy: 0.9756 - loss: 0.0715
Epoch 917/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.9566 - loss: 0.0900 
Epoch 918/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - categorical_accuracy: 0.9480 - loss: 0.1031 
Epoch

In [ ]:
rede_neural.evaluate(X_teste, y_teste)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - categorical_accuracy: 1.0000 - loss: 0.0498 


[0.04695489630103111, 1.0]

In [ ]:
previsoes = rede_neural.predict(X_teste)
previsoes

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[5.28981445e-06, 9.99939382e-01, 5.53075879e-05],
       [3.89454219e-10, 2.21089635e-04, 9.99778986e-01],
       [1.01586784e-05, 9.99148428e-01, 8.41342029e-04],
       [1.17264944e-08, 2.69859191e-03, 9.97301400e-01],
       [2.01538865e-06, 1.04036309e-01, 8.95961642e-01],
       [1.42257470e-10, 1.80038318e-04, 9.99819994e-01],
       [9.99839544e-01, 1.34956645e-04, 2.56166331e-05],
       [2.25961721e-05, 9.96410131e-01, 3.56735429e-03],
       [1.47535920e-05, 3.69156957e-01, 6.30828321e-01],
       [2.55793509e-07, 1.80240080e-01, 8.19759607e-01],
       [9.99815941e-01, 1.56515307e-04, 2.76883129e-05],
       [1.66761602e-05, 9.96024609e-01, 3.95878870e-03],
       [3.89792698e-10, 1.68607105e-04, 9.99831438e-01],
       [2.58232512e-06, 4.80855823e-01, 5.19141555e-01],
       [9.99991119e-01, 4.43653380e-06, 4.43296858e-06],
       [9.99988258e-01, 6.44779766e-06, 5.19229252e-06],
       [9.11320583e-08, 2.62254546e-03, 9.97377336e-01],
       [9.99985993e-01, 8.04785

In [ ]:
previsoes = previsoes > 0.5
previsoes

array([[False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [ T

In [ ]:
y_teste2 = [np.argmax(t) for t in y_teste]
previsoes2 = [np.argmax(t) for t in previsoes]


In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_teste2, previsoes2)

1.0

In [ ]:
confusion_matrix(y_teste2, previsoes2)

array([[14,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 15]])

In [37]:
rede_neural.save('modelo_iris.h5')

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ipywidgets import interact, widgets

sns.set(style="whitegrid")

class_names = ['Setosa', 'Versicolor', 'Virginica']

def predict_and_visualize(sepal_length, sepal_width, petal_length, petal_width):
    new_observation = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
    prediction = rede_neural.predict(new_observation)
    predicted_class = np.argmax(prediction)
    predicted_class_name = class_names[predicted_class]

    print(f"\033[1mPredicted class:\033[0m {predicted_class_name} (index: {predicted_class})")
    print(f"Prediction probabilities: {prediction[0]}")

    # Plot
    plt.figure(figsize=(8, 5))
    bars = sns.barplot(x=class_names, y=prediction[0], palette='Set2')
    plt.title("Probability per Iris Species", fontsize=14)
    plt.xlabel("Species")
    plt.ylabel("Probability")
    plt.ylim(0, 1)

    # Add labels on top of each bar
    for i, p in enumerate(prediction[0]):
        bars.text(i, p + 0.02, f"{p:.2f}", ha='center', fontsize=12, weight='bold')

    plt.tight_layout()
    plt.show()

# Sliders (sem mudanças)
sepal_length_slider = widgets.FloatSlider(min=4, max=8, step=0.1, value=5.8, description="Sepal Length:")
sepal_width_slider = widgets.FloatSlider(min=2, max=4.5, step=0.1, value=3, description="Sepal Width:")
petal_length_slider = widgets.FloatSlider(min=1, max=7, step=0.1, value=4, description="Petal Length:")
petal_width_slider = widgets.FloatSlider(min=0.1, max=2.5, step=0.1, value=1.2, description="Petal Width:")

interact(predict_and_visualize,
         sepal_length=sepal_length_slider,
         sepal_width=sepal_width_slider,
         petal_length=petal_length_slider,
         petal_width=petal_width_slider);


interactive(children=(FloatSlider(value=5.8, description='Sepal Length:', max=8.0, min=4.0), FloatSlider(value…

In [46]:
import gradio as gr

#rede_neural = keras.models.load_model('modelo_iris.h5')

class_names = ['Setosa', 'Versicolor', 'Virginica']

def predict_iris(sepal_length, sepal_width, petal_length, petal_width):
    new_observation = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
    prediction = rede_neural.predict(new_observation)
    return {class_names[i]: float(prediction[0][i]) for i in range(3)}

# Interface Gradio
iface = gr.Interface(
    fn=predict_iris,
    inputs=[
        gr.Slider(4, 8, value=5.8, label="Sepal Length"),
        gr.Slider(2, 4.5, value=3.0, label="Sepal Width"),
        gr.Slider(1, 7, value=4.0, label="Petal Length"),
        gr.Slider(0.1, 2.5, value=1.2, label="Petal Width"),
    ],
    outputs=gr.Label(num_top_classes=3),
    title="🌸🥀 Deep learning para previsão: Iris",
    description="Use os controles para prever a espécie de uma flor Iris com uma rede neural treinada."
)

# Executar localmente
iface.launch(inbrowser=True)






It looks like you are running Gradio on a hosted a Jupyter notebook. For the Gradio app to work, sharing must be enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://f608fae540be1e0d9a.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [ ]:
from scikeras.wrapeprs import KerasClassifier
from sklearn.preprocessing import LabelEncoder
